spring.application.name=algafood-api
spring.profiles.active=develop
server.port = 8082

notificador.email.port-servidor=28

#spring.jpa.generate-ddl=true
#spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect