spring.application.name=algafood-api
spring.profiles.active=develop
server.port = 8081

notificador.email.port-servidor=28

spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=create

spring.jpa.show-sql=true
spring.jpa.propoerties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect